title: "Li Yantao's Blog"
description: "Research blog of Li Yantao"
url: ""
baseurl: ""

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

collections:
  publications:
    output: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - bin
  - dist
  - .ruby-version
